apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}-deployment
  namespace: {{ template "gateway.namespace" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | indent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: gateway
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ template "gateway.fullname" . }}-container
          envFrom:
          - secretRef:
              name: {{ template "gateway.fullname" . }}-secret
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key | upper }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if not .Values.serviceMonitor.enabled }}
          - name: MONITORING
            value: "false"
          {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: fastapi
            - containerPort: {{ .Values.service.monitorPort }}
              name: monitoring
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- $root := . }}
      {{- range .Values.image.pullSecrets }}
        - name: {{ tpl . $root }}
      {{- end}}
      {{- end }}
      serviceAccountName: {{ template "gateway.serviceAccountName" . }}
