apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gateway-api-server.fullname" . }}-deployment
  namespace: {{ template "gateway-api-server.namespace" . }}
  labels:
    {{- include "gateway-api-server.labels" . | nindent 4 }}
    {{- if .Values.labels }}
    {{ toYaml .Values.labels | indent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "gateway-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway-api-server.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: gateway-api-server
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          {{- if not .Values.serviceMonitor }}
          - name: MONITORING
            value: "false"
          {{- end }}
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ template "gateway-api-server.fullname" . }}-container
          envFrom:
          - secretRef:
              name: {{ template "gateway-api-server.fullname" . }}-secret
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: {{ template "gateway-api-server.fullname" . }}-port
          {{- with .Values.livenessProbe }}
          livenessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ template "gateway-api-server.serviceAccountName" . }}