apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway-api-server.fullname" . }}-secret
  namespace: {{ template "gateway-api-server.namespace" . }}
  labels:
    {{- include "gateway-api-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.config }}
  {{ $key | upper }}: {{ tpl $value $ | quote }}
  {{- end }}
#  SENTRY_DSN: aHR0cHM6Ly9mYWJiNGVkN2UzZjE5ZGJjOGRkODVkMmU4YzcyOTI3MkBvNDUwNDYwOTE0MTg4Mjg4MC5pbmdlc3Quc2VudHJ5LmlvLzQ1MDU4NDM2MTQ0ODI0MzI=
