apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "gateway.fullname" . }}-servicemonitor
  namespace: {{ template "gateway.namespace" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    release: jina-prom
spec:
  endpoints:
    - port: monitoring
  namespaceSelector:
    matchNames:
      - {{ template "gateway.namespace" . }}
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
