apiVersion: v1
kind: Service
metadata:
  name: {{ template "gateway.fullname" . }}-service
  namespace: {{ template "gateway.namespace" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort:  {{ .Values.containerPort }}
      name: fastapi
    - port: {{ .Values.service.monitorPort }}
      targetPort: {{ .Values.service.monitorPort }}
      name: monitoring