{{- if and .Values.apimanager.enable .Values.operator.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "api-manager.fullname" . }}-secret
  namespace: {{ template "jina-operator.namespace" . }}
  labels:
    {{- include "api-manager.labels" . | nindent 4 }}
{{- with .Values.apimanager.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  mongo-url: {{ .Values.apimanager.config.mongo.url | b64enc | quote }}
{{- end }}