{{- if and .Values.operator.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "jina-operator.labels" . | nindent 4 }}
{{- with .Values.operator.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "jina-operator.fullname" . }}-manager
rules:
- apiGroups:
    - jcloud.jina.ai
  resources:
    - flows
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
    - deletecollection
- apiGroups:
    - jcloud.jina.ai
  resources:
    - flows/finalizers
  verbs:
    - update
- apiGroups:
    - jcloud.jina.ai
  resources:
    - flows/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - ""
  resources:
    - persistentvolumeclaims
    - persistentvolumes
    - services
    - pods
    - configmaps
    - deployments
    - statefulsets
    - secrets
    - namespaces
    - events
    - replicasets
  verbs: 
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "apps"
  resources:
    - deployments
    - replicasets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "apps"
  resources:
    - statefulsets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "batch"
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - watch
- apiGroups:
    - "networking.k8s.io"
  resources:
    - ingresses
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "configuration.konghq.com"
  resources:
    - kongingresses
    - kongplugins
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "monitoring.coreos.com"
  resources:
    - servicemonitors
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - "serving.knative.dev"
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
    - serviceaccounts
    - namespaces/status
    - pods/log
    - pods/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "jina-operator.labels" . | nindent 4 }}
{{- with .Values.operator.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "jina-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "jina-operator.labels" . | nindent 4 }}
{{- with .Values.operator.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ template "jina-operator.fullname" . }}-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
{{- end}}
