{{- if .Values.operator.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jina-operator.fullname" . }}-secret
  namespace: {{ template "jina-operator.namespace" . }}
  labels:
    {{- include "jina-operator.labels" . | nindent 4 }}
{{- with .Values.operator.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  mongo-url: {{ .Values.operator.config.mongo.url | b64enc | quote }}
{{- end }}