{{- if .Values.operator.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "jina-operator.labels" . | nindent 4 }}
  {{- with .Values.operator.rbac.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- $root := . }}
{{- with .Values.operator.rbac.serviceAccount.annotations }}
  annotations:
{{ tpl (toYaml . | indent 4) $root }}
{{- end }}
  name: {{ template "jina-operator.serviceAccountName" . }}
  namespace: {{ template "jina-operator.namespace" . }}
{{- end }}